(*************************************************************************)
(*                                                                       *)
(*                                OCaPIC                                 *)
(*                                                                       *)
(*                             Benoit Vaugon                             *)
(*                                                                       *)
(*    This file is distributed under the terms of the CeCILL license.    *)
(*    See file ../../LICENSE-en.                                         *)
(*                                                                       *)
(*************************************************************************)

let ofs = 0xF00

let porta    = 0xF80
let portb    = 0xF81
let portc    = 0xF82
let portd    = 0xF83
let porte    = 0xF84
let lata     = 0xF89
let latb     = 0xF8A
let latc     = 0xF8B
let latd     = 0xF8C
let late     = 0xF8D
let trisa    = 0xF92
let trisb    = 0xF93
let trisc    = 0xF94
let trisd    = 0xF95
let trise    = 0xF96
let osctune  = 0xF9B
let pie1     = 0xF9D
let pir1     = 0xF9E
let ipr1     = 0xF9F
let pie2     = 0xFA0
let pir2     = 0xFA1
let ipr2     = 0xFA2
let eecon1   = 0xFA6
let eecon2   = 0xFA7
let eedata   = 0xFA8
let eeadr    = 0xFA9
let eeadrh   = 0xFAA
let rcsta    = 0xFAB
let txsta    = 0xFAC
let txreg    = 0xFAD
let rcreg    = 0xFAE
let spbrg    = 0xFAF
let spbrgh   = 0xFB0
let t3con    = 0xFB1
let tmr3l    = 0xFB2
let tmr3h    = 0xFB3
let cmcon    = 0xFB4
let cvrcon   = 0xFB5
let eccp1as  = 0xFB6
let pwm1con  = 0xFB7
let baudcon  = 0xFB8
let ccp2con  = 0xFBA
let ccpr2l   = 0xFBB
let ccpr2h   = 0xFBC
let ccp1con  = 0xFBD
let ccpr1l   = 0xFBE
let ccpr1h   = 0xFBF
let adcon2   = 0xFC0
let adcon1   = 0xFC1
let adcon0   = 0xFC2
let adresl   = 0xFC3
let adresh   = 0xFC4
let sspcon2  = 0xFC5
let sspcon1  = 0xFC6
let sspstat  = 0xFC7
let sspadd   = 0xFC8
let sspbuf   = 0xFC9
let t2con    = 0xFCA
let pr2      = 0xFCB
let tmr2     = 0xFCC
let t1con    = 0xFCD
let tmr1l    = 0xFCE
let tmr1h    = 0xFCF
let rcon     = 0xFD0
let wdtcon   = 0xFD1
let hlvdcon  = 0xFD2
let osccon   = 0xFD3
let t0con    = 0xFD5
let tmr0l    = 0xFD6
let tmr0h    = 0xFD7
let status   = 0xFD8
let fsr2l    = 0xFD9
let fsr2h    = 0xFDA
let pusw2    = 0xFDB
let preinc2  = 0xFDC
let postdec2 = 0xFDD
let postinc2 = 0xFDE
let indf2    = 0xFDF
let bsr      = 0xFE0
let fsr1l    = 0xFE1
let fsr1h    = 0xFE2
let plusw1   = 0xFE3
let preinc1  = 0xFE4
let postdec1 = 0xFE5
let postinc1 = 0xFE6
let indf1    = 0xFE7
let wreg     = 0xFE8
let fsr0l    = 0xFE9
let fsr0h    = 0xFEA
let plusw0   = 0xFEB
let preinc0  = 0xFEC
let postdec0 = 0xFED
let postinc0 = 0xFEE
let indf0    = 0xFEF
let intcon3  = 0xFF0
let intcon2  = 0xFF1
let incon    = 0xFF2
let prodl    = 0xFF3
let prodh    = 0xFF4
let tablat   = 0xFF5
let tblptrl  = 0xFF6
let tblptrh  = 0xFF7
let tblptru  = 0xFF8
let pcl      = 0xFF9
let pclath   = 0xFFA
let pclatu   = 0xFFB
let stkptr   = 0xFFC
let tosl     = 0xFFD
let tosh     = 0xFFE
let tosu     = 0xFFF
